// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "retos_moure_dev_swift",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "retos_moure_dev_swift",
            targets: ["AppModule"],
            bundleIdentifier: "asaekkpp.retos-moure-dev-swift",
            teamIdentifier: "KGAZ44YFLQ",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .dog),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
